version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3
    working_directory: ~/vim-jp
    steps:
      - checkout
      - restore_cache:
          keys:
            - vim-jp-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile" }}
            - vim-jp-{{ arch }}-{{ .Branch }}
            - vim-jp-
      - run:
          name: Install Ruby dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 && bundle clean -V
      - save_cache:
          key: vim-jp-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
      - run:
          name: Build the Jekyll site
          command: bundle exec jekyll build -d jekyll/_site/docs/
      - store_artifacts:
          path: jekyll/_site/docs/
          destination: vim-jp.github.io
      - run:
          name: List generated files
          command: find jekyll/_site/docs/ -type f
